#!/bin/bash
if [ -z "$JAVA" ]; then
    if [ -n "$JAVA_HOME" ]; then
        JAVA="$JAVA_HOME/bin/java"
    else
        JAVA="java"
    fi
fi

eval "$JAVA"c ReplLoader.java
ADMCLI=integration/client-cli/admin-cli
CRYDFT=crypto/default
# cry fps ;)
CRYFPS=crypto/fips1402
for mroot in "$ADMCLI" "$CRYDFT" "$CRYFPS" ; do
  ( 
    cd "$mroot"
    mvn -Dmaven.tests.skip=true verify
  )
done
#if [[ $? == "0" ]] ; then ...
